Add app version convention
nullindustries/code_style pull request #11
Opened 2016-09-07 15:25 UTC by danielgomezrico

2016-09-07 17:33 UTC, orendon commented on README.md
> +- Mobile Clients will send a header `bv-app-version` with the app version for each api request.
+1 for `"bv-user-agent" "platform-version"`
with `platform` being either `android` or `ios` and version following semver standars

2016-09-07 19:14 UTC, danielgomezrico commented on README.md
> +- Mobile Clients will send a header `bv-app-version` with the app version for each api request.
+1 orendon idea

2016-09-08 16:12 UTC, earayo commented on README.md
> +- Mobile Clients will send a header `bv-app-version` with the app version for each api request.
¿What happens if we have one or more mobile application for each platform. For example an application for customer and another application for admin?
I believe the `bv-app-version` should contain `platform/typeAppr/version`; 
`platform`: maybe `android` or `iOS`
`typeApp`: i.e `Customer` or `admin`
`version`: following semver standars (`x.y.z`)

2016-09-08 16:14 UTC, danielgomezrico commented
@earayo +1 idea!

2016-09-08 16:15 UTC, danielgomezrico commented on README.md
> +- Mobile Clients will send a header `bv-app-version` with the app version for each api request.
@earayo +1 edward idea `platform/typeApp/version`

2016-09-08 21:13 UTC, Busta117 commented on README.md
> +- Mobile Clients will send a header `bv-app-version` with the app version for each api request.
we can add "build" at the end... so,  `platform/typeApp/version/build`

2016-09-21 22:16 UTC, Busta117 commented on README.md
> +- Mobile Clients will send a header `bv-app-version` with the app version for each api request.
so.. `platform/typeApp/version/build` where:
`platform` : platform who make the request in **lower case** (ej: `ios`, `android`)
`typeApp` :  app profile who make the request in **lower case** (ej: `customer`, `driver`, `admin`) if there are only one app could be `mobile` for mobile apps
`version` : current app version following semver standard (`x.y.z`)
`build` : current build version, could be empty, number or letters 

am i right?

2016-12-16 14:31 UTC, lordaniel commented on README.md
> +    - `build : current build version, could be empty, number or letters
@caipivara Is missing an end ` for build ?

2016-12-16 15:32 UTC, orendon commented on README.md
> +    - `build : current build version, could be empty, number or letters
Good catch

2016-12-16 15:33 UTC, orendon approved these changes
Besides the lord comment :shipit:

2016-12-16 16:28 UTC, lordaniel approved these changes
@caipivara Good Job

2016-12-19 15:30 UTC, edwaraco requested changes
@caipivara Good job!  I add a comment for your consideration.

2016-12-19 15:30 UTC, earayo commented on README.md
> +    - `build` : current build version, could be empty, number or letters
I don't like the build could be empty. What do you think about to avoid it?

2016-12-19 18:24 UTC, edwaraco requested changes
Good job. I added some more silly comments.

2016-12-19 18:24 UTC, earayo commented on README.md
> +    - `platform` :***mandatory*** platform who make the request in lower case (ej: ios, android)
What do you think:
`platform` (***mandatory***): ...

2016-12-19 18:24 UTC, earayo commented on README.md
> +    - `typeApp` :***mandatory*** app profile who make the request in lower case (ej: customer, driver, admin) if there are only one app could be mobile for mobile apps
Same here.
`typeApp` (***mandatory***): ...

2016-12-19 18:24 UTC, earayo commented on README.md
> +    - `version` :***mandatory*** current app version following semver standard (x.y.z)
Same here:
`version` (***mandatory***): ...

2016-12-19 18:24 UTC, earayo commented on README.md
> +    - `build` :***optional*** current build version, could be number or letters
Wdyt?
`build` (***optional***): ...

2016-12-19 18:42 UTC, edwaraco approved these changes
@Busta117 and @caipivara good job. I'm sorry for my dyslexia.

2016-12-19 18:42 UTC, merged