Force Update Error Format
nullindustries/code_style pull request #16
Opened 2017-03-12 13:36 UTC by Busta117

2017-03-16 15:52 UTC, caipivara commented
@Busta117 we will have more than one error format? current format is:

```
{
  "errors": {
    "field1": "message1",
    "field2": "message2"
  }
}
```

2017-03-16 15:53 UTC, danielgomezrico requested changes

2017-03-16 15:53 UTC, caipivara commented on backend/README.md
> +  "errors": {
the content of `errors` is not multiple errors, it looks weird to me.

2017-04-12 20:43 UTC, earayo commented on backend/README.md
> +  "errors": {
@caipivara Errors may content multiples attributes with errors. For this reason, they are wrapped in `errors`.

2017-04-14 19:34 UTC, caipivara commented on backend/README.md
> +  "errors": {
@earayo but what I mean is that errors have two different formtats, one for errors where key is the reason of the error and another for force update with `url` and `message` field.

2017-04-20 23:56 UTC, orendon approved these changes
I agree here, actually MedAnswers and Lenspire are following this convention already.

2017-04-25 17:22 UTC, orendon commented on backend/README.md
> +  "errors": {
The force update proposed by @Busta117 is ok, and it's being used now in all projects.

Let's continue the general error handling strategy on #18

2017-04-25 17:36 UTC, danielgomezrico approved these changes

2017-04-25 17:37 UTC, merged