Fix wrong style for bv-app-version info
nullindustries/code_style pull request #17
Opened 2017-04-17 19:36 UTC by caipivara

2017-04-17 20:00 UTC, edwaraco requested changes
@caipivara I prefer to keep the current style.

2017-04-17 20:00 UTC, earayo commented on README.md
> +    - `platform`: platform who make the request in lower case (ej: ios, android)
I prefer to know what is mandatory.

2017-04-17 20:05 UTC, caipivara commented on README.md
> +    - `platform`: platform who make the request in lower case (ej: ios, android)
@earayo I prefer say just whats optional like swagger models :P, but the fix is not for that, is to fix a markdown issue

2017-04-20 23:50 UTC, orendon approved these changes
I like this 👍

2017-04-20 23:58 UTC, Busta117 approved these changes
👍

2017-04-25 17:33 UTC, merged